#########################################################
# This file contains a function that given a number of  #
# observations n, and a number of folds K returns       #
# randomly assigned foldids to fold k=1, 2, ..., K      #
# for n ids. Also containt function to adapt the format #
# to the form that is required for the packages         #
# CoxBoost and mboost.                                  #
#########################################################

Kfold <- function(n, K){
  ## Function that assigns n observations to K
  ## folds of roughly equal size.
  foldids <- c()
  if ( n > K) {
    for (k in 1:(ceiling(n/K) - 1)){
      foldids <- c(foldids, 1:K)
    }
    foldids <- c(foldids, sample(x=1:K,
                                 size= n - (ceiling(n/K)*K - K),
                                 replace = FALSE))
  }
  if (n == K){
    foldids <- 1:n
  }
  return (sample(x=foldids, size=n, replace = FALSE))  
  
}

CoxBoostKfold <- function(n, K){
  ## Function that adapts Kfold to the input required
  ## for CoxBoost to assign fold-ids to observations
  return(Kfold2CoxBoostKfold(Kfold(n, k)))
}

Kfold2CoxBoostKfold <- function(foldids){
  ## Function that converts foldids generated by Kfold to
  ## the format required for CoxBoost
  
  # CoxBoost is backwards, so need to invert the foldids
  # into list of indices per fold
  folds <- vector("list", 10)
  for (i in 1:length(foldids)) {
    folds[[foldids[i]]] <- c(i, folds[[foldids[i]]])  
  }
  return(folds)
}

Kfold2MboostKfold <- function(foldids){
  # Mboost is also quirky, need an indicator matrix of an observation being contained in the
  # k-th fold
  folds.mboost <- matrix(rep(1, length(foldids)*max(foldids)), nrow = length(foldids),
                         ncol = max(foldids))
  for(i in 1:length(foldids)){
    folds.mboost[i, foldids[i]] <- 0
  }
  return(folds.mboost)
}

MboostKfold <- function(n, K){
  ## Function that adapts Kfold to the input required
  ## for CoxBoost to assign fold-ids to observations
  return(Kfold2MboostKfold(Kfold(n, k)))
}